
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver	
hikari:
 maximum-pool-size: 50
 minimum-idle: 10
 connection-timeout: 30000
 idle-timeout: 60000
 max-lifetime: 1800000
 
jpa:
    properties.hibernate-dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate.ddl-auto: update

